### ISSUE TITLE
Drop Repo Concept

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#15]
With changes to how configuration data is going to be added it feels appropriate to drop the `repo` concept entirely, including:
- Removing repo commands
- Removing repo directory

The only part of the repo, really, is the `config` stuff so `/var/lib/underware/config` would suffice. 

As part of this the refactor of the directory structure would be ideal, like:
- `/opt/underware/templates/orchestration/`
- `/opt/underware/templates/platform/`
- `/opt/underware/templates/plugins/`
- `/opt/underware/templates/genders`
- `/opt/underware/config/domain.yaml`
- `/opt/underware/configure.yaml`

The files to include can be found at:
- [`config/domain.yaml`](https://raw.githubusercontent.com/ste78/wip/stustuff/underware/repo/config/domain.yaml)
- [`configure.yaml`](https://raw.githubusercontent.com/ste78/wip/stustuff/underware/repo/configure.yaml)
- [`genders/default`](https://raw.githubusercontent.com/ste78/wip/stustuff/underware/repo/genders/default)

The refactor is worth considering with #14

**Comment by bobwhitelock** [comment]
Long term: we should include the type of the scope in the `config` path, similarly to with `answers`, e.g. `/opt/underware/data/config/domain.yaml` vs `/opt/underware/data/config/nodes/domain.yaml` rather than have the potential for conflicts between these.

**Comment by bobwhitelock** [comment]
Also: to keep everything confined in one place we should probably stick all these files under `/data` (i.e. `/opt/underware/data` when Underware is installed) rather than at the top level.

**Comment by bobwhitelock** [comment]
From meeting earlier:
- Underware repo will be removed and relevant existing files/new files will be merged into `data` directory, in directory structure described in https://github.com/alces-software/underware/issues/19.
- Can ignore `templates` dir structure above in favour of this, and in particular let's not consider plugins for now as not sure how these fit into things.
