### ISSUE TITLE
Implement `template` command

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#19]
Whether this is a modification to the `render` command or an addition of a new sort of rendering command, this enhancement addresses the need for file management within Underware.

It should be able to logically work out a place to put files, it may just be as simple as having a "render map" file that has key/value pairs to determine which input files go where or take some argument that can define the output path. 

It's safe to assume that all rendered content will end up at `/var/lib/underware/rendered/<platform>/<scope>/` but determining where underneath the `<scope>` directory (which could be anything from `node01` to `myprimarygroup` to `domain`)  is something that will need some deliberation

**Comment by bobwhitelock** [comment]
Plan from meeting discussion earlier:

- Within Underware, both in this project and when installed, we will have the following directory hierarchy:
  ```
  - data/templates/
    - genders
    - (and similarly for any other internal, root-level templates which might
      exist in future; currently none that I know of)

    - aws/
      - domain/
      - group/
      - node/

    - azure/
      - domain/
      - group/
      - node/
    - etc., and similarly for all platforms

    - content/
      - domain/
      - group/
      - node/
        - here and for specific platforms above, anything can go under these
          directories in any directory hierarchy; this is all just content
  ```

- The new `template` command will:
  - Work out what all the distinct scopes of the cluster to render for are. Currently these will consist of:
    - a single domain
    - every Underware-configured group (but not every genders group)
    - every node

  - For every platform `$platform_name`:
    - For each `$scope` as found above, of type `$scope_type` (currently `domain`, `group`, or `node`) :
      - Create `$platform_scope` by merging the platform-specific config into the `$scope` config

      - combine templates in `templates/$platform_name/$scope_type/*` and `templates/content/$scope_type/*`
        - Aside: duplicate files can be considered an error, but we control these directories so we can just not do this/consider this undefined behaviour for now, and/or just merge the platform templates on top of the shared templates since these are more specific

      - For each template:

        - Each template will have an (arbitrarily nested) `$path`, relative to the `templates/$platform_name/$scope_type/` directory

        - Render template against the `$platform_scope` scope, to `/var/lib/underware/rendered/$platform_name/$scope_name/$path`, where `$scope_name` is:
          - `/domain` for domain scope
          - `/group/${group.name}` for group scope
          - `/node/${node.name}` for node scope


- Additional notes related to the above:
  - There will be no platform-specific handling needed in Underware itself
    - the only prerequisite for a platform `$platform_name` to exist and have files rendered for it as far as Underware is concerned is for a directory `data/templates/$platform_name/` with some content to exist; then when `template` is run everything within this directory will be rendered as described above, and the platform will also be available anywhere else Underware will deal with platforms

  - we will hold off on any special handling of partial template rendering within templates for now - if needed absolute paths can just be used to reference partials in templates (e.g. `<%= scope.render_file '/opt/underware/data/partials/my_partial.erb' %>`)

**Comment by bobwhitelock** [comment]
Change to above re:
> the only prerequisite for a platform `$platform_name` to exist and have files rendered for it as far as Underware is concerned is for a directory `data/templates/$platform_name/` with some content to exist; then when `template` is run everything within this directory will be rendered as described above, and the platform will also be available anywhere else Underware will deal with platforms

following https://github.com/alces-software/underware/pull/29, this will now be handled like this instead:
> The existence of a config file `data/config/platforms/${platform}.yaml` means that the `$platform` platform exists

This will make it clearer for a user to see what platforms are currently available, and for us to add or remove platforms on the fly as needed. This also means we will be able to render just the `content` files with a new configuration by just creating a new platform config file, without needing to create any platform-specific templates, which might be useful for experimentation.
