### ISSUE TITLE
Have `interface` question type, and use this for `configured_build_interface` question

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/underware#25]
When a configuration question is given `type: interface`, this should function like a `choice` question (i.e. offer a set list of choices and require one of these to be chosen before proceeding), but the available values should be determined at runtime to be `Underware::Network.interfaces` rather than specified in the `configure.yaml` file.

This should remove the possibility of a user specifying an invalid interface and then being confused when they get many weird errors related to an IP being unable to be resolved on this interface (at least apart from edge cases like an interface later disappearing after the user has chosen it but before they have rendered templates).

**Comment by bobwhitelock** [comment]
@ColonelPanicks let me know what you think about this, and how much of a priority you think it is.

If this doesn't make much sense at the moment it will probably make more sense after you've seen my changes related to https://github.com/alces-software/underware/issues/15 (basically `build_interface` is configured by a question in `configure.yaml` now rather than hard-coded in `server.yaml`, which makes it clearer how to configure this and what this does, and removes another dependency on the Underware repo, but does mean a user needs to choose this potentially with no context about what interfaces are available).

**Comment by ColonelPanicks** [comment]
I think having it as a question is suitable for now. Priority for being smarter with it is pretty much the same as the other helpers (#18 and #16) so not highest for now.

The information that always escapes me is why we need to specify the build_interface, do you happen to recall why we need it in the first place? You mention that it needs to resolve an IP address, so this is done by querying an interface? And where in the namespace is this IP used? 

Sorry for the questions, I'm sure it's back somewhere in the metalware repo but since things have evolved a bit into Underware I think it's worth re-clarifying.

**Comment by bobwhitelock** [comment]
Thanks for answering, I think this is probably worth doing at some point but is just another thing we can do to streamline the cluster creation process, and not absolutely essential.

> The information that always escapes me is why we need to specify the build_interface, do you happen to recall why we need it in the first place? You mention that it needs to resolve an IP address, so this is done by querying an interface? And where in the namespace is this IP used?

So at the moment I believe we use it:

- To determine the IP of the deployment server (i.e. the machine Underware is currently running on) - this is then used to determine various values in the namespace like:
  - `domain.hostip`
  - `domain.hosts_url`
  - `domain.genders_url` 
  - `node.kickstart_url`
  - `node.build_complete_url`
  
  We need to get this IP on a particular interface as this needs to be an IP for the deployment server which will be accessible to nodes across the cluster, as these values will then be used (for Metalware) in various rendered files so that nodes can retrieve other files from/report back to the deployment server; we can't always use a specific interface or guess an interface as I believe the particular interface we want to use will vary depending on the machine Underware/Metalware is installed on and the particular build we're doing.

- As the interface to listen for new nodes on in `metal hunter` (so we'll probably need to consider how this will need to change when we update Metalware following this batch of Underware changes, since it's no longer coming from the repo). This similarly needs to be a particular interface which the nodes will come up on, and so similarly can vary between builds (and is usually/always(?) the same interface as above, hence why we share the same value for this).

So both of these reasons are currently fairly specific to bare metal builds, but I think it makes sense for this stuff to stay living in Underware since Underware will soon be rendering all templates. There's also nothing in principle which would stop us in future from rendering cloud templates which use the IP of the Underware machine in future, e.g. if we're running an Underware machine in the cloud and want to launch other nodes and then get files/report back to the original machine, in a similar way to how we build bare metal clusters.

> Sorry for the questions, I'm sure it's back somewhere in the metalware repo but since things have evolved a bit into Underware I think it's worth re-clarifying.

No problem, I think this is worth doing too :slightly_smiling_face:.

**Comment by bobwhitelock** [comment]
A thought: we could reduce the need for manually configuring the build interface by adding a bit more logic to this question type as well. Some thoughts on this:

1. When both choosing the options for an `interface` question and choosing the default interface if a user hasn't yet configured this, we could remove the `lo` option as it doesn't make sense to use the loopback interface when building a cluster. I.e. we will never want to listen for nodes coming up on this interface in `metal hunter`, which will never happen, and we never want templates rendered for nodes to include URLs like `127.0.0.1/metalware/kickstart/node01`, which would mean trying to retrieve local rather than controller files (I'm mostly guessing about this, @ColonelPanicks or @ste78 can probably confirm if it's a reasonable assumption to remove this option).

2. From the remaining interfaces, we can remove the need to make any choice if only one other interface is available, and just use this transparently to the Underware user.

3. We could make asking this question in the first place conditional on the type of cluster being built in some way - e.g. we could have cloud and metal-specific questions in `configure.yaml`, and only bother asking this question if a cloud cluster is being built, to avoid confusing the user by having them make a choice which is ultimately irrelevant (this would mean we'd need to not render the bare metal build files in this case, once https://github.com/alces-software/underware/issues/19 has been implemented, otherwise these would either all error or all be filled with potentially junk values).

**Comment by ColonelPanicks** [comment]
In relation to your thoughts:
1. That makes complete sense. We still need to find somewhere sane to put hunter and it being part of metalware seems the most appropriate for now considering that mac address collection is a metal-specific task.
2. 👍 
3. I believe in both cases of metal and cloud we'd want the build interface even if it's not something we're building over. In cases of the build complete URL, named zones and hosts/genders upstream URLs it isn't a metal-specific need to know the IP of the controller/underware master.

**Comment by bobwhitelock** [comment]
Thanks for the answers. Re:

> I believe in both cases of metal and cloud we'd want the build interface even if it's not something we're building over. In cases of the build complete URL, named zones and hosts/genders upstream URLs it isn't a metal-specific need to know the IP of the controller/underware master.

I guess this depends on the content we create for the `aws`, `azure`, etc providers - if we never use any of these values which use the Controller IP, then asking the user to provide the interface that this should be determined on doesn't seem worth doing and could confuse them. If we do use it or may use it in future then having this just part of the standard process seems worthwhile.

It could also just be worth asking always since, given that [the `template` command](https://github.com/alces-software/underware/issues/19) will render all templates for all platforms, having this value always available after configuration will remove the need for us to do any special filtering to conditionally render templates depending on whether it's available (I think I've convinced myself that just always asking this question if we can't automatically determine the interface is the better option, doing anything else seems more trouble than it's worth).

**Comment by ColonelPanicks** [comment]
As you mention we will be rendering templates for _all_ platforms (perhaps making that configurable going forward) so I think always ensuring that a value is set for build interface is the way to go.

I was hoping that we could retire it completely but that would mean either a) lots of wizardry to identify what interface/IP to use for these values or b) manually specifying the IP address in all areas that require it. Both of which aren't ideal so having a bit of internal magic along with a question will be suitable.

Thanks Bob!
