### ISSUE TITLE
Do we need a way to make the available platforms discoverable?

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/underware#43]
Currently, the only way to see what platforms are available within Underware is to run `template` or to inspect the content within this repo. Maybe we need a command to list these, and/or a `platforms` part of the namespace to iterate through the available platforms?

**Comment by ColonelPanicks** [comment]
I don't really think this is necessary at the current point in development. All platforms are dealt with at once when templating so I do not believe we need a particular `list` command and that this can just be covered in documentation.
