### ISSUE TITLE
Suggested namespace-related refactoring

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/underware#44]
A few suggestions I've recently noted when touching these classes, for refactoring to make the namespace-related code clearer; implement or ignore at your leisure :slightly_smiling_face::

- Rename `Namespaces::Alces` to something like `Namespaces::RootNamespace`;
  indicates actual purpose of this class

- Rename `Namespaces::HashMergerNamespace` something like `Namespaces::AbstractNamespace` to indicate this is the parent class for other (non-root) namespaces and not an actual namespace in itself

- Inline `Mixins::WhiteListHasher` in `Namespaces::HashMergerNamespace`, as this is only place it's used
  - could refactor to do this by:
    - inline and adjust the `WhiteListHasher` tests to test the overall class
    - when inlining, should also be able to simplify to remove unnecessary genericness e.g. methods raising `NotImplementedError` which then are implemented in the single user of the module
    - reorganize the inlined code to be separate object used by `HashMergerNamespace`, rather than all dumped in together

- Remove unnecessary creation and use of `Constants::HASH_MERGER_DATA_STRUCTURE`, and just use the referenced class
  directly

**Comment by WilliamMcCumstie** [comment]
The `WhilteListHasher` could be replaced by checking the `arity` of each method. If the `arity` is 0 then it can be called without any input and thus should be added to the hash.

Possible generate the list as the methods are being defined using `method_added`
