### ISSUE TITLE
Consider removing the legacy Underware installer

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/underware#45]
This will not actually work at the moment as no `dist` files have been uploaded for `el6`, and the installation steps have also not been updated along with various recent changes. It is also likely not worth updating as this is unlikely to ever be used again. It is possibly still worth keeping the handling for installing for different distros so can handle `el8` when that comes along, and/or so can add handling for other distros if ever needed in future.

Similar probably also applies to Metalware.

**Comment by WilliamMcCumstie** [comment]
Can the entire installer be binned? Fundamentally this is a ruby app and `bundle install` should be sufficient. Possible a `rake install` command to handle the fact its both an `app` and a `gem`.

However an entire install shouldn't be required. There is a bit of an issue getting `nodeattr`, however this could be handled by using the system version. See #50

**Comment by WilliamMcCumstie** [comment]
The installer has been removed
