### ISSUE TITLE
Init Process and Cluster Overlays

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#67]
## Issue

There are concerns that the `underware init` command has become unclear and that content related to it will become unmanageable. 

Currently, there are two ways of running init:
- `underware init CLUSTER` - This creates CLUSTER with a copy of the data from `data/` and configure groups for login and compute nodes (using the data from `data/init`), adding configuration overrides for the node `gateway1` (from `data/config/gateway1.yaml`) in order for it to work as a gateway node
- `underware init CLUSTER --bare` - This create CLUSTER with a copy of the data from `data/`

The main concern of @WilliamMcCumstie is that having override config and answer files which ship with Underware require additional maintenance to reflect default content configuration.

The main concern of @ColonelPanicks is that the init process is blurring the example/demo cluster into the standard init process while the data is somewhat obfuscated in `data/`.

## Resolution

Through IRL discussion with @WilliamMcCumstie we have established that the above concerns can be addressed by:

1. Improving the structure of the `data/` directory
  1.1. `data/bare` for all of the default content
  1.2. `data/example` for the example cluster overrides (containing what is currently at `data/config/gateway1.yaml` and `data/init/`)
2. Move the example cluster logic into some sort of config/spec file within the `data/example` directory
3. Adding a command flag to `init` for handling what "overlay" will be used for the cluster

## Advantages of Resolution

Creating this "overlay" concept brings us logical separation between `init` behaviour and content overrides which allows for easier maintenance and potential expansion towards "cluster profiles".

## Feedback

@ste78 and @mjtko - It would be good to get your opinion on this issue and resolution before we crack ahead with implementation.

**Comment by ColonelPanicks** [comment]
Approved by @ste78 IRL

**Comment by WilliamMcCumstie** [comment]
Implemented in #69
