### ISSUE TITLE
Make the `events_dir` user content

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/underware#77]
`Underware` still needs to know about the `events_dir` used by metalware:
https://github.com/alces-software/underware/blob/8624f78d45fda850d8b0a007c3afdfa978ce2799/lib/underware/config.rb#L73-L81

This is only relevant to `metalware` builds so it seems a bit odd having it embedded in `underware's` general configuration. Instead this feels more fitting somewhere in `configs/domain.yaml`. This will allow it to be set on a per cluster bases as well.

This change will also correspond with the removal of `events` from the core `underware` code:
https://github.com/alces-software/underware/blob/8624f78d45fda850d8b0a007c3afdfa978ce2799/lib/underware/namespaces/node_prototype.rb#L71
https://github.com/alces-software/underware/blob/8624f78d45fda850d8b0a007c3afdfa978ce2799/lib/underware/file_path.rb#L49

**Comment by WilliamMcCumstie** [comment]
@ColonelPanicks Could you have a look at changing the content, so `underware` doesn't need to know about it?

Once you have, create a PR and I'll tack on the internal changes

**Comment by ColonelPanicks** [comment]
@WilliamMcCumstie as it currently stands, no content in Underware uses the events directory.

With kickstart builds, [there is a PHP script that is curled which puts any event files into place](https://github.com/alces-software/metalware-repo-base/blob/master/files/core/configs/kscomplete.php). 

Some of the old local node content may have used the events directory stuff but I believe, as you suggest, that if/when content needs to know about this (for the kickstart builds taking place in metalware) that the events directory can be fully managed within content 😄
