### ISSUE TITLE
Add back validation of rendered `genders`

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/underware#8]
This existed in Metalware when `genders` was rendered via staging, but was very coupled with the `sync`ing process - it would be nice to have this back now this rendering has been moved to Underware. Refer to https://github.com/alces-software/underware/commit/562a2e51966ca51f30a24f03dbd19e82d2113919.

**Comment by WilliamMcCumstie** [comment]
Genders is no longer being used
