### ISSUE TITLE
Rendering File Names

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#96]
Add a method for being able to rename rendered files.

For example, the AWS template for a node is stored at `aws/node/node.yaml`, instead of each node in a cluster containing `node.yaml` it would be preferred to have the template named after the node.

From discussions IRL, the suggested method is that `__node.name__`/`__group.name__`/etc in filenames are replaced during rendering.

**Comment by WilliamMcCumstie** [comment]
Implemented in `2019.1.0-rc9`

Instead of having group/node specific tagging, it is a single `__name__` filename that is replaced
