### ISSUE TITLE
Separate Platform and Content Data in Rendered Data

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#97]
In response to the export capabilities of Underware and the importing through Cloudware it has come to our attention that Cloudware importing _all_ the rendered data for a given platform is unnecessary (it has no need for networking setup scripts, etc). It was also determined that Cloudware scrubbing the entire rendered contents for a node to find a template would also be prone to issues.

The solution here is to separate platform and content information in the rendered directory. This way, any platform orchestration tools know which sub-directory to look into for necessary files. It's worth doing the same with the content too (such that any general content is unable to overwrite platform files).

E.g.:
```shell
# Current layout
[root@controller mycluster]# ls var/rendered/aws/node/gateway1/
base  cloudimage  main.sh  networking  node.yaml

# New layout
[root@controller mycluster]# ls var/rendered/aws/node/gateway1/
content  orchestration
[root@controller mycluster]# ls var/rendered/aws/node/gateway1/orchestration/
cloudimage  node.yaml
[root@controller mycluster]# ls var/rendered/aws/node/gateway1/content/
base  main.sh  networking
```

**Comment by WilliamMcCumstie** [comment]
Fixed in `2019.1.0-rc9`
